# define the language used
language: node_js
node_js:
- stable

# docker as service for localstack
services:
  - docker

# manually install terraform CLI
before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
  - unzip terraform_0.11.3_linux_amd64.zip

# export access keys for terraform
# since we use it only locally, the keys can be nonsense
# also we start the localstack image
# init terraform
# start npm test
script:
  - export AWS_ACCESS_KEY_ID="ANYKEY"
  - export AWS_SECRET_ACCESS_KEY="ANYSECRET"
  - docker run -d \
   -p 4567-4578:4567-4578 -p 8080:8080 \
   localstack/localstack
  - ./terraform init
  - TF_EXEC=./terraform npm t
