# define the language used
language: node_js
node_js:
- stable

# manually install terraform CLI
before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
  - unzip terraform_0.11.3_linux_amd64.zip

script:
  - export AWS_ACCESS_KEY_ID="ANYKEY" && export AWS_SECRET_ACCESS_KEY="ANYSECRET"
  - TF_EXEC=./terraform npm t
